In [2]:
# Imports - avoid importing multiple copies
import pandas as pd
import sqlite3
from decimal import Decimal
import locale

In [7]:
# Write some code to step through a "month" column in a Dataframe containing month names and filter out the invalid entries
data = {'Month': ['January', 'February', 'March', 'April', 'May', 'InvalidMonth', 'July']}
dfData = pd.DataFrame(data=data)

AllowedMonths = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]

dfDataFiltered = dfData[dfData["Month"].str.upper().isin(AllowedMonths)]

display(dfData)
display(dfDataFiltered)

          Month
0       January
1      February
2         March
3         April
4           May
5  InvalidMonth
6          July

      Month
0   January
1  February
2     March
3     April
4       May
6      July

In [ ]:
# Pat Lacey's solution to the above.
# Read data into DataFrame
data = {'Month': ['January', 'February', 'March', 'April', 'May', 'InvalidMonth', 'July']}
df = pd.DataFrame(data)
df

# Create the list of valid months
verified_months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'November', 'October', 'December']
# Create the list that will filter the DataFrame
filter = []

# Iterate through the column
for i in range(0, len(df['Month'])):
    # Find the value of the iteration
    month = df.loc[i,'Month']
    # Check if the value is present in the list of valid months
    # Append True to keep the row, append False to filter it out
    if month in verified_months:
        filter.append(True)
    else:
        filter.append(False)

# Once the filter list is full, use it to filter the DataFrame
subset = df[filter]
subset

# Here is a one line solution that follows the same logic
df = df[df['Month'].isin(verified_months)]
df